<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>Astar.DatabaseBypass</AssemblyName>
    <RootNamespace>Astar.DatabaseBypass</RootNamespace>
    <Version>0.1.0</Version>
    <PackageLicenseExpression>CC-BY-NC-SA-4.0</PackageLicenseExpression>
    <Authors>Astar</Authors>
    <Copyright>Copyright © 2026 Astar</Copyright>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\..\artifacts\bin\$(Configuration)\</OutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SPT.Server">
      <HintPath>$(SptServerRoot)\SPT.Server.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.Server.Core">
      <HintPath>$(SptServerRoot)\SPTarkov.Server.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.Reflection">
      <HintPath>$(SptServerRoot)\SPTarkov.Reflection.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.Common">
      <HintPath>$(SptServerRoot)\SPTarkov.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.DI">
      <HintPath>$(SptServerRoot)\SPTarkov.DI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SemanticVersioning">
      <HintPath>$(SptServerRoot)\SemanticVersioning.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(SptServerRoot)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
